spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Landt@0812
    url: jdbc:mysql://localhost:3306/rms
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB          
 
file:
  upload-directory: D:/PTiT/DATN/rms_data/

security:
  jwt:
    secret-key: thisisasecretkeyofdinhtronglan

